url: "http://aix-marseille.afup.org"

title: "AFUP Aix-Marseille"
description: >
  Antenne AFUP sur Aix-en-Provence et Marseille
twitter_username: AFUP_AixMrs
meetup_url: "https://www.meetup.com/fr-FR/afup-aix-marseille-php/"

permalink: /posts/:title

ga_ua: "G-54QC9YDH3Y"
home_featured_articles_count: 1

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
   - Makefile
   - docker-compose.yml
   - docker-compose.override.yml-dist
   - docker-compose.override.yml
   - Gemfile
   - Gemfile.lock

feed:
  path: feed

